### ISSUE TITLE
Suggestion for ABS

### ISSUE THREAD

**Issue by ModMike** [3dprintingworld/MULDEX#1]
I love the design and can't wait to build one. I hope it's not presumptuous of me to make a suggest a suggestion.

Could you modify the design to mount the electronics outside the build chamber and plan for a fully enclosed system to allow for a heated chamber?

I guess the electronics could be sealed off but I think it might be cleaner to mount them outside the build chamber. I would also like to avoid having to build a hat to enclose the machine.

It's nice to see a design from a real engineer!

**Comment by sorren4** [comment]
I would imagine that you could use most/all of the same mount points for the electronics, etc. internally but mount them to the other side of the same panel holes.  I know that's a technical possibility with my Railcore as long as I didn't want to use the same panels on the inside as I have around the electronics on the outside.

**Comment by 3dprintingworld** [comment]
The frame could definitely be extended to enclose the chamber.  Since I built it for MRRF I wanted it to be open so people can see the belt kinematics easier so I did not enclose it.  My thought was that the motors and electronics would stay where they are but I would extend the wall all the way up between them.

**Comment by ModMike** [comment]
The Muldex screams ABS :-)

**Comment by 3dprintingworld** [comment]
> The Muldex screams ABS :-)

I agree, with all the motors stationary mounted behind the frame would make it perfect.
